### PR TITLE
Refactor PE image section handling. Add debug logging.

### PR DESCRIPTION
**Pull request by neerajsi-msft**
Encapsulate dwarf-related PE sections into a new class.  Remove some
unused sections.

Move the context set via DIECursor::setContext to be static members of
the class and add a debug context there.

Add a standard method of enabling debug logging across the dwarf and PDB
code.

These are prep changes for supporting DWARF5

### CODE REVIEW

**Comment by neerajsi-msft** [comment]
@dscho : this is a prep patch for dwarf5 support.

**Comment by dscho** [comment]
> @dscho : this is a prep patch for dwarf5 support.

Thank you!

@rainers FYI @neerajsi-msft noticed that the function symbols are missing from the output of `cv2pdb` when processing executables produced by GCC v11.x, and is working on extending the DWARF5 support _properly_ (i.e. cleaning up after the mess I left by implementing "too little" of DWARF5 support).

**Review by dscho — COMMENTED** [review]
Disclaimer: I am _not_ the maintainer of this project, so take all of my comments with a grain of salt.

I had a look through the changes, and they look pretty sound. However, I would have preferred the changes to be split into a series of commits that would have been easier to review (and would have made it harder for bugs to slip through the review).

For example, the change making `debug` a non-Boolean would make for a natural, easy-to-review commit, as would be the changes that drop commented-out code or noops. Likewise, dropping the unused fields `debug_aranges`, `debug_pubnames` and `debug_pubtypes` would make for another commit that would be very easy to validate. Then, a commit that turns `debug_info` and friends into `PESection`s would make for another really clear commit. And finally, adding the sections that haven't been there before (`debug_addr`, `debug_loclists` and `debug_rnglists`) would be another quite neat commit.

If you could [split the commit](https://git-scm.com/docs/git-rebase#_splitting_commits) accordingly, I am sure it would be more convenient for the `cv2pdb` maintainer to gain confidence in this PR's modifications.

**Comment by neerajsi-msft** [comment]
Thanks for the feedback Johannes.  I have another PR in the stack at https://github.com/neerajsi-msft/cv2pdb/pull/1.

I didn't want to make too many PRs and commits since it's harder to ensure that each one is actually tested.

**Comment by neerajsi-msft** [comment]
I'm closing this PR in favor of a single PR that implements all of dwarf5 support.

We can split that PR as appropriate according to Rainer's wishes.

**Pull request closed without merging**
